### ISSUE TITLE
update from v4.4.5 -> v4.4.7 fails without error

### ISSUE THREAD

**Issue by gr2m** [nodejs/installer#20]
I love the idea for a native app to install Node :)

I just gave it spin. It showed me correctly that my node version is out of date and I could press the update button. And it seemed to have worked, but after it’s done it reverts to the same view again

![screen shot 2016-07-01 at 17 30 45](https://cloud.githubusercontent.com/assets/39992/16534985/d413f436-3fb1-11e6-867c-342e2350c663.png)

Here is what the logs say:

```
$ npm start

> installer@0.1.0 start /Users/gregor/Projects/node-installer
> electron .

2016-07-01 17:29:21.339 Electron[44432:8884808] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 3. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
sudo: a password is required
installer: Package name is Node.js
installer: Installing at base path /
installer: The install was successful.
```

**Comment by ryanmurakami** [comment]
@gr2m Try closing and reopening the installer. I experienced the same thing, and it seems that it's not updating the version after installation.

**Comment by gr2m** [comment]
that was my very first run ^^

Restarted the installer, same result. I also get a prompt to enter my sudo password, not sure if that’s intended. Happy to leave my node version as is for some time and help debugging the issue

**Comment by ryanmurakami** [comment]
@gr2m Do you use a version manager like nvm? You can also check your PATH to ensure something isn't resolving node before the vanilla install. Another thing to do is check the version of the node binary in /usr/local/bin.

**Comment by gr2m** [comment]
Yes, I use `nvm`, is that the problem?

```
$ which node
/Users/gregor/.nvm/versions/node/v4.4.5/bin/node
```

**Comment by ryanmurakami** [comment]
@gr2m Oh cool. Yep, I believe it is. The node installer is going to update the binary in /usr/local/bin, not where nvm is installing. And, if your PATH, is anything like mine, the nvm directories are at the front, and therefore resolve `node` before /usr/local/bin. In another issue, I believe you can execute `nvm use system` to grab the updated version.

**Comment by gr2m** [comment]
yeah I can confirm that the node at `/usr/local/bin` has been updated. 

```
$ /usr/local/bin/node -v
v4.4.7
```

Maybe let’s update the README unless you have an idea how to make it work with `nvm`?

**Comment by ryanmurakami** [comment]
@gr2m Ok, good. Yeah, I did open #19, but I won't have time to work on it anytime soon. Maybe you or someone else can give it a shot? ;-)

**Comment by ljharb** [comment]
@gr2m What happens if you `nvm use system`?

**Comment by gr2m** [comment]
```
$ nvm use system
Now using system version of node: v4.4.7
```

**Comment by gr2m** [comment]
I’m okay closing this now in favor of #19. Thanks folks!
