### ISSUE TITLE
Installer UI

### ISSUE THREAD

**Issue by delvedor** [nodejs/installer#26]
Hi all,
while we are discussing about code style and other stuff, I want to open another topic: the Installer UI.

I made some experiments, and I've created this, what do you think?
Any constructive suggestion is welcome!

![node js installer](https://cloud.githubusercontent.com/assets/4865608/16928863/3cdddde8-4d35-11e6-84d6-6ce55b61f249.png)

If you like it, I can start to write some code :)

**Comment by azat-co** [comment]
@delvedor nice but I don't think news should take so much space... if you are a beginner you need to download installs first and reading the news is secondary... maybe swap them?

Ed resources can benefits from a logo too. See how I did it in https://github.com/nodejs/installer/pull/22#issuecomment-231517666

**Comment by delvedor** [comment]
@azat-co can be a good idea make a check if node is installed in the system, if not, we visualize only the "install" part, then the interface you see above.
In the white part on the right we can use two tabs navigable with dots, one for the news and one for the educational resources, maybe with some code snippet.
Agree for the logo of the educational resources.

**Comment by mikeal** [comment]
I like it a lot, but I would hold off on the "News" section. It's a bit too much info and is mostly unnecessary for newer users.

**Comment by delvedor** [comment]
I totally agree that the installer must be newbie friendly, but I think it must be intermediate/advanced friendly as well :)

My proposal it to use tabs to switch between arguments (see the dots on the top), such as _Educational section_ or _News section_ (now I'm using "News" because the loren ipsum is too mainstream, but it can be anything).

![node js installer v2 0](https://cloud.githubusercontent.com/assets/4865608/17085719/74eea218-51df-11e6-9e99-8656bb19dddc.png)

**Comment by Qard** [comment]
I would expect most of the users of the graphical installer would be newbies. Power users would probably stick to their command-line tools, like nvm. I don't think news has all that much value in the installer. I'd prefer we keep it simple and only include some brief info to direct newbies on how to get started.

**Comment by delvedor** [comment]
Again, the "News" is not a proposal, I've put them here just to explain that we can write a lot of different informations and not only the newbie ones.
If the News section is a problem, I can substitute it with a Loren Ipsum ;)

**Comment by Fishrock123** [comment]
I like it, but it would be more useful to link to just that release blog rather than "news" imo.

**Comment by JoeDoyle23** [comment]
Thanks so much for your work on updating the UI!
