### ISSUE TITLE
Include release notes for latest builds

### ISSUE THREAD

**Issue by trstringer** [nodejs/installer#27]
At the very least, release notes for the latest builds should be included.  This should eventually include a diff of release notes from currently installed build to latest, as well as highlighting security-related patches.

**Comment by delvedor** [comment]
I've made a first proposal of the Installer UI and I've included a news feed as you can see here #26.
Is something like this what do you mean?

**Comment by trstringer** [comment]
I don't think a news feed would include the entire information of release notes.  Right?  That would especially get difficult when trying to compile patches between multiple versions.

**Comment by delvedor** [comment]
Obviously not, but the news feed could include various links to interesting/important topics :)

**Comment by trstringer** [comment]
Don't get me wrong, newsfeed is better than nothing. But hopefully there's a way to make a call to get release notes.

**Comment by delvedor** [comment]
@tstringer let me understand, what you mean by _"make a call to get release notes"_?
Something like an http-call to get [this](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md) informations? :)

**Comment by mikeal** [comment]
Full release notes a bit much for new users. A link to the release notes would definitely be good though, especially when there is an upgrade.

It's important to remember who the target audience is: people who currently have a hard time installing and upgrade Node.js. The kind of people who will dig into the release notes are probably already fine installing and upgrading node.js.
