### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by williamkapke** [nodejs/installer#29]
Please add License info to the README. The `package.json` says it is Apache-2.0.

**Comment by JoeDoyle23** [comment]
@mikeal: Let us know if Apache-2.0 is the correct license and we'll get this taken care of.

**Comment by williamkapke** [comment]
Ping @mikeal

**Comment by mikeal** [comment]
Because it was created as Apache-2 we should keep it that way. If we want to change the license we'd have to get the permission of everyone who has contributed so far.

**Comment by mikeal** [comment]
BTW, Apache-2 is an approved license in the foundation. We're suppose to default to MIT but we can bring in projects in a variety of liberal licenses (BSD, Apache-2, etc).
