### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by delvedor** [nodejs/installer#34]
Hi all!
Is this project dead? Suspended? Waiting for some decision from [version-management](https://github.com/nodejs/version-management)?

Thanks!

cc: @mikeal @addaleax

**Comment by addaleax** [comment]
I think it’s mostly in a “nobody feels overly responsible for it” kind of state… if you feel like you are somebody who’d want to go ahead and take the lead on this project yourself (which, you know, would be *beyond awesome*), we can probably make that happen?

I’d still be happy to help out with reviewing code & testing it…

@williamkapke Where are the rules for what a project like this needs (governance docs etc.)?

**Comment by mikeal** [comment]
Anyone who gets in a PR will be given commit rights.

Anyone who wants to jump in and lead this I'd love to help you do that :)

**Comment by addaleax** [comment]
Ok, then I’m *definitely* adding @delvedor as a committer. :D

**Comment by delvedor** [comment]
As you both know, in the past months I've contributed to this project by designing and implementing the new UI, I would be very happy to continue the job!

But right know I am not very experienced of how conduct a project like this inside the Node org. So if I have to take this responsibility (and I would), I'd really appreciate some help/advice from you :)

**Comment by delvedor** [comment]
Thank you @addaleax! :)

**Comment by mikeal** [comment]
@delvedor let's get a Google Hangout OnAir going with the existing project contributors about next steps and I can answer any questions you have about how to drive this stuff :)

**Comment by addaleax** [comment]
@nodejs/electron-installer ^

(@delvedor You should be able to @mention that team now, too :))

**Comment by delvedor** [comment]
@mikeal that would be awesome!
Thank you all! :)
