### ISSUE TITLE
Show educational resources after installation.

### ISSUE THREAD

**Issue by mikeal** [nodejs/installer#4]

**Comment by evanlucas** [comment]
I think this should include a link directly to the docs for the version installed

**Comment by mikeal** [comment]
The API docs aren't a great resource for _learning_ Node.js. I was thinking of something more like nodeschool. /cc @hackygolucky

**Comment by evanlucas** [comment]
fair enough

**Comment by SomeoneWeird** [comment]
+1 for nodeschool after install

**Comment by azat-co** [comment]
how about something like #22? 
![screenshot 2016-07-01 22 34 17](https://cloud.githubusercontent.com/assets/1137314/16538524/fbd7342c-3fdb-11e6-87d1-bc8aed534b83.png)

**Comment by delvedor** [comment]
I've made an UI proposal which shows the Educational resources, take a look :)
#26

**Comment by delvedor** [comment]
I think this can be closed.
