### ISSUE TITLE
repost from `nodejs/version-management` - The Windows installer (a.k.a the 🐘 in the room)

### ISSUE THREAD

**Issue by refack** [nodejs/installer#49]
> So for some unknown historical reason node core has a Windows installer (probably to appease the MS gods)...
> After a recent conversation with @ljharb, IMHO the installer should be in this WG's focus, since it's essentially a "management-challenged" version manager....
> We are fielding issues as:
> * [Allow multiple installs of Node on Windows with msi](https://github.com/nodejs/node/issues/4603)
> * [Stop the installer deleting my symlink for AppData\Roaming\npm](https://github.com/nodejs/node/issues/7882)
> * [Windows installer: Per user install (feature request)](https://github.com/nodejs/node/issues/13830)
> [and the list goes on...](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Awindows%20label%3Ainstall)
> 
> Which bring up the same issues that are discussed here, like:
> * where do we put the global `node_modules`?
> * Should we install `npm` or not, and where?
> * Does `core` want to officially support side-by-side multi-version, and if so how to switch versions (i.e. version manager yes or no)?
> * How to detect which version are installed?
> 
> Not to diminish from this WG's efforts in the least, and not intending to step on anyone's toes!!!
> It's just that our questions are less "academic" since they are motivated by issues opened by users, since the Windows installer is unfortunately an existing core feature 🤦‍♂️ So we need to answer them sooner rather than later...
> BTW: Personally my prefered answer would have been "The Windows installer is deprecated, use the zipped package or a userland version manager" but it got push-back https://github.com/nodejs/node/issues/4603#issuecomment-313275229
> 
> /cc @tniessen @nodejs/platform-windows

**Comment by benjamingr** [comment]
Let's either keep the discussion here or there but not in both places?

**Comment by refack** [comment]
I don't want to fragment either so lets keep it there (https://github.com/nodejs/version-management/issues/16). Just wanted to bring it to this group's attention.
