### ISSUE TITLE
Get into the Apple App Store.

### ISSUE THREAD

**Issue by mikeal** [nodejs/installer#6]

**Comment by ChALkeR** [comment]
Does it comply with Apple App Store restrictions?

I'm pretty sure that it doesn't.

> **2.5.2** Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code, including other iOS, watchOS, Mac OS X, or tvOS apps.

and

> **2.4.5** Apps distributed via the Mac App Store have some additional requirements to keep in mind:
> …
>   **(ii)** They must be packaged and submitted using technologies provided in Xcode; no third party installers allowed. They must also be self-contained, single application installation bundles and cannot install code or resources in shared locations.
> …
>  **(iv)** They may not download or install standalone apps, kexts, additional code, or resources to add functionality or significantly change the app from what we see during the review process.
>  **(v)** They may not request escalation to root privileges or use setuid attributes.
>  **(vi)** They may not present a license screen at launch, require license keys, or implement their own copy protection.
>  **(vii)** They must use the Mac App Store to distribute updates; other update mechanisms are not allowed.

Refs: https://developer.apple.com/app-store/review/guidelines/

**Comment by jlord** [comment]
Electron apps, on the latest version, are compatible with the Mac App Store. There are certain things you may have to do, depending on what your app does, to give it the permissions Apple requires.
- [Electron Guide](http://electron.atom.io/docs/tutorial/mac-app-store-submission-guide)
- We just got Electron API App in the MAS, here's [the relevant PR](https://github.com/electron/electron-api-demos/pull/214/files)

**Comment by develar** [comment]
@jlord After #17 packaging for MAS is simple, `npm run dist -- --mac mas` ;) electron-builder allows you to avoid such boilerplate code for each project.

**Comment by ChALkeR** [comment]
@jlord 

> Electron apps, on the latest version, are compatible with the Mac App Store. There are certain things you may have to do, depending on what your app does, to give it the permissions Apple requires.

Hm. Ok, that's cool. I don't think that the actual _download and install Node.js_ part is compatible with App Store, though.

**Comment by 75lb** [comment]
sorry to disturb this thread but has @ChALkeR 's account been hacked? I'm receiving private email and gitter messages encouraging me to contact him/her for something "urgent" regarding npm tokens.. just smells a bit phishy..

**Comment by ChALkeR** [comment]
@75lb No, it hasn't. I contacted you privately for a reason, and that doesn't have anything to do with this thread.

**Comment by felixrieseberg** [comment]
Sorry to poop on everyone's parade, but this won't be possible. Writing data outside the sandbox is a big no-no, and installing Node.js won't be possible with an MAS bundle.

**Comment by ChALkeR** [comment]
@felixrieseberg That's basically what I have been trying to tell above…

No positive activity for a year, also it doesn't look like this is possible at all due to App Store rules.
Closing.

Feel free to reopen though =).
