### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by geek** [nodejs/installer#9]

**Comment by SomeoneWeird** [comment]
What are we thinking? I see semicolons being preferred, soo semistandard? 😁

**Comment by cjihrig** [comment]
I propose https://www.npmjs.com/package/node-style. It's Node core's ESLint setup.

**Comment by delvedor** [comment]
I propose Standard, because is the Electron code style :)

**Comment by geek** [comment]
@SomeoneWeird @delvedor I don't care what the linting style is, I only care that there is one.  Node.js already has a linting style, this repo is under nodejs, thus the chosen linting style in order to be consistent.

**Comment by mikeal** [comment]
I think we should go with standard. Sure, core has a style, but people who contribute to electron apps a probably more familiar with standard.

**Comment by JoeDoyle23** [comment]
To end the discussion, I created a PR that implements standard and fixes any current violations.
